// Generated by gencpp from file imu_parser/IMUData.msg
// DO NOT EDIT!


#ifndef IMU_PARSER_MESSAGE_IMUDATA_H
#define IMU_PARSER_MESSAGE_IMUDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_parser
{
template <class ContainerAllocator>
struct IMUData_
{
  typedef IMUData_<ContainerAllocator> Type;

  IMUData_()
    : heading(0.0)  {
    }
  IMUData_(const ContainerAllocator& _alloc)
    : heading(0.0)  {
  (void)_alloc;
    }



   typedef double _heading_type;
  _heading_type heading;





  typedef boost::shared_ptr< ::imu_parser::IMUData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_parser::IMUData_<ContainerAllocator> const> ConstPtr;

}; // struct IMUData_

typedef ::imu_parser::IMUData_<std::allocator<void> > IMUData;

typedef boost::shared_ptr< ::imu_parser::IMUData > IMUDataPtr;
typedef boost::shared_ptr< ::imu_parser::IMUData const> IMUDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_parser::IMUData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_parser::IMUData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_parser::IMUData_<ContainerAllocator1> & lhs, const ::imu_parser::IMUData_<ContainerAllocator2> & rhs)
{
  return lhs.heading == rhs.heading;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_parser::IMUData_<ContainerAllocator1> & lhs, const ::imu_parser::IMUData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_parser

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_parser::IMUData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_parser::IMUData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_parser::IMUData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_parser::IMUData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_parser::IMUData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_parser::IMUData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_parser::IMUData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9635d0d9f52c085a5bcd934107785851";
  }

  static const char* value(const ::imu_parser::IMUData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9635d0d9f52c085aULL;
  static const uint64_t static_value2 = 0x5bcd934107785851ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_parser::IMUData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_parser/IMUData";
  }

  static const char* value(const ::imu_parser::IMUData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_parser::IMUData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 heading\n"
;
  }

  static const char* value(const ::imu_parser::IMUData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_parser::IMUData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IMUData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_parser::IMUData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_parser::IMUData_<ContainerAllocator>& v)
  {
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_PARSER_MESSAGE_IMUDATA_H
