// Generated by gencpp from file relay/Steer.msg
// DO NOT EDIT!


#ifndef RELAY_MESSAGE_STEER_H
#define RELAY_MESSAGE_STEER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace relay
{
template <class ContainerAllocator>
struct Steer_
{
  typedef Steer_<ContainerAllocator> Type;

  Steer_()
    : steer(0)
    , speed(0)  {
    }
  Steer_(const ContainerAllocator& _alloc)
    : steer(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef int8_t _steer_type;
  _steer_type steer;

   typedef int8_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::relay::Steer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::relay::Steer_<ContainerAllocator> const> ConstPtr;

}; // struct Steer_

typedef ::relay::Steer_<std::allocator<void> > Steer;

typedef boost::shared_ptr< ::relay::Steer > SteerPtr;
typedef boost::shared_ptr< ::relay::Steer const> SteerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::relay::Steer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::relay::Steer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::relay::Steer_<ContainerAllocator1> & lhs, const ::relay::Steer_<ContainerAllocator2> & rhs)
{
  return lhs.steer == rhs.steer &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::relay::Steer_<ContainerAllocator1> & lhs, const ::relay::Steer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace relay

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::relay::Steer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::relay::Steer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::relay::Steer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::relay::Steer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::relay::Steer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::relay::Steer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::relay::Steer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fdd80fb67c06e0f36269df15172b228";
  }

  static const char* value(const ::relay::Steer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fdd80fb67c06e0fULL;
  static const uint64_t static_value2 = 0x36269df15172b228ULL;
};

template<class ContainerAllocator>
struct DataType< ::relay::Steer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "relay/Steer";
  }

  static const char* value(const ::relay::Steer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::relay::Steer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 steer\n"
"int8 speed\n"
;
  }

  static const char* value(const ::relay::Steer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::relay::Steer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steer);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Steer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::relay::Steer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::relay::Steer_<ContainerAllocator>& v)
  {
    s << indent << "steer: ";
    Printer<int8_t>::stream(s, indent + "  ", v.steer);
    s << indent << "speed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RELAY_MESSAGE_STEER_H
