// Generated by gencpp from file controller/ControllerOut.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_CONTROLLEROUT_H
#define CONTROLLER_MESSAGE_CONTROLLEROUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller
{
template <class ContainerAllocator>
struct ControllerOut_
{
  typedef ControllerOut_<ContainerAllocator> Type;

  ControllerOut_()
    : steer(0)
    , speed(0)  {
    }
  ControllerOut_(const ContainerAllocator& _alloc)
    : steer(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef int8_t _steer_type;
  _steer_type steer;

   typedef int8_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::controller::ControllerOut_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::ControllerOut_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerOut_

typedef ::controller::ControllerOut_<std::allocator<void> > ControllerOut;

typedef boost::shared_ptr< ::controller::ControllerOut > ControllerOutPtr;
typedef boost::shared_ptr< ::controller::ControllerOut const> ControllerOutConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::ControllerOut_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::ControllerOut_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller::ControllerOut_<ContainerAllocator1> & lhs, const ::controller::ControllerOut_<ContainerAllocator2> & rhs)
{
  return lhs.steer == rhs.steer &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller::ControllerOut_<ContainerAllocator1> & lhs, const ::controller::ControllerOut_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller::ControllerOut_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::ControllerOut_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::ControllerOut_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::ControllerOut_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::ControllerOut_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::ControllerOut_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::ControllerOut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fdd80fb67c06e0f36269df15172b228";
  }

  static const char* value(const ::controller::ControllerOut_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fdd80fb67c06e0fULL;
  static const uint64_t static_value2 = 0x36269df15172b228ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::ControllerOut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/ControllerOut";
  }

  static const char* value(const ::controller::ControllerOut_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::ControllerOut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 steer\n"
"int8 speed\n"
;
  }

  static const char* value(const ::controller::ControllerOut_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::ControllerOut_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steer);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerOut_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::ControllerOut_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::ControllerOut_<ContainerAllocator>& v)
  {
    s << indent << "steer: ";
    Printer<int8_t>::stream(s, indent + "  ", v.steer);
    s << indent << "speed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_CONTROLLEROUT_H
